---
title: "Lab 03 - Great Lakes Fish Stocking"
author: "Kristina Totoraitis"
date: "02-16-23"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
fish_stock <- read_csv("data/great-lakes-fish-stock.csv")
```

## Exercises

### Exercise 1

8 columns & 56,232 rows 

### Exercise 2

```{r}
salmon_stock <- fish_stock %>%
  filter(
    SPECIES %in% c("ATS", "CHS", "COS"),
    !is.na(WEIGHT),
      LAKE != "ON"
  )
```
```{r}
salmon_stock %>%
  glimpse()
```

There are 56,232 rows & 8 columns, there are 5 numerical variables & 3 character strings. 

### Exercise 3

```{r}
salmon_stock %>%
  mutate(
    SALMON_WEIGHT_G = WEIGHT / NO_STOCKED * 1000
  )
```

The mutate function is creating the average weight variable. 
### Exercise 4

```{r}
salmon_stock %>% 
  group_by(LAKE) %>% 
  filter(YEAR > 2000) %>% 
  summarize(MEAN_NO_STOCKED = mean(NO_STOCKED, na.rm = TRUE),
            MEAN_WEIGHT = mean(WEIGHT, na.rm = TRUE)) %>% 
  arrange(desc(MEAN_WEIGHT))
```


### Exercise 5
```{r}
Trout_stock <- fish_stock %>%
  filter(
    SPECIES %in% c("BKT", "BRN", "LAT", "TRT"),
    !is.na(WEIGHT),
      LAKE != "ON"
  )
```
```{r}
Trout_stock %>%
  glimpse()
```

ˆ


```{r}
Trout_stock %>%
  mutate(
    Trout_WEIGHT_G = WEIGHT / NO_STOCKED * 1000
  )
```
```{r}
Trout_stock %>% 
  group_by(LAKE) %>% 
  filter(YEAR > 2000) %>%
  summarize(MEAN_NO_STOCKED = mean(NO_STOCKED, na.rm = TRUE),
            MEAN_WEIGHT = mean(WEIGHT, na.rm = TRUE)) %>% 
  arrange(desc(MEAN_WEIGHT))
```



### Exercise 6
```{r}
fish_stock%>%
  filter( SPECIES== "CHS"|SPECIES== "BKT")%>% 
group_by(YEAR, LAKE, SPECIES)%>% summarise(SUM_ANNUAL= sum(NO_STOCKED, na.rm=TRUE)) %>% 
ggplot(aes( x= YEAR, y= SUM_ANNUAL, color= SPECIES))+ geom_line()+ 
  facet_wrap(~ LAKE)+ theme_bw()
```

